name = "openheatpumps-backend"
main = "backend/index.js"
compatibility_date = "2024-03-01"

[vars]
# Let op: De GEMINI_API_KEY configureren we als Secret in het dashboard, die zetten we hier niet in tekst neer .

[[d1_databases]]
binding = "D1_DB"
database_name = "openquatt-db"
database_id = "676f322e-af02-4f92-9fcb-7f1949f23281"
